### ISSUE TITLE
panic: interface conversion: dns.RR is *dns.OPT, not *dns.A

### ISSUE THREAD

**Issue by palsivertsen** [yyyar/gobetween#97]
Using Docker image yyyar/gobetween:0.4.0 generates the following panic when looking up SRV records:

```# gobetween -c gbt.toml 
2017-06-28 11:30:25 [INFO ] (manager): Initializing...
2017-06-28 11:30:25 [INFO ] (udp/server): Creating UDP server 'some-server': :5683 weight srv none
2017-06-28 11:30:25 [INFO ] (scheduler): Starting scheduler
2017-06-28 11:30:25 [INFO ] (manager): Initialized
2017-06-28 11:30:25 [INFO ] (api): API disabled
2017-06-28 11:30:25 [INFO ] (srvFetch): Fetching 10.0.0.2:53 some-service.some-domain.
panic: interface conversion: dns.RR is *dns.OPT, not *dns.A

goroutine 12 [running]:
_/home/ubuntu/git_projects/gobetween/src/discovery.srvFetch(0xc420192c38, 0x3, 0xa4195c, 0x3, 0xa41087, 0x1, 0xa41087, 0x1, 0x0, 0xc4201a4030, ...)
	/home/ubuntu/git_projects/gobetween/src/discovery/srv.go:67 +0x92b
_/home/ubuntu/git_projects/gobetween/src/discovery.(*Discovery).Start.func1(0xc420190d20, 0xc420019a40, 0x0)
	/home/ubuntu/git_projects/gobetween/src/discovery/discovery.go:101 +0x67
created by _/home/ubuntu/git_projects/gobetween/src/discovery.(*Discovery).Start
	/home/ubuntu/git_projects/gobetween/src/discovery/discovery.go:131 +0x136
```

gbt.toml:

```[servers.some-server]
bind = ":5683"
protocol = "udp"

        [servers.some-server.discovery]
        kind = "srv"
        srv_lookup_server = "10.0.0.2:53"
        srv_lookup_pattern = "some-service.some-domain."
```

**Comment by yyyar** [comment]
@palsivertsen thanks for the issue!
That definitely looks like gobetween bug. 
gobetween expects SRV and A records in DNS response, but gets OPT record.

What DNS server are you using? Could you please copy-paste here output of 
`dig SRV @10.0.0.2 -p 53 some-service.some-domain.`
If will help us debug it easier.

**Comment by palsivertsen** [comment]
I am using AWS Route 53 and AWS DNS servers. Using Go's `net.LookupSRV("", "", "some-service.some-domain")` works fine.

Dig SRV:
```
# dig SRV @10.0.0.2 -p 53 influx.test.platform-services.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> SRV @10.0.0.2 -p 53 influx.test.platform-services.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58760
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;influx.test.platform-services.	IN	SRV

;; ANSWER SECTION:
influx.test.platform-services. 0 IN	SRV	1 1 32769 ip-10-0-1-121.eu-west-1.compute.internal.

;; Query time: 1 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Tue Jul 04 07:24:01 UTC 2017
;; MSG SIZE  rcvd: 118
```
Dig A:
```
# dig A @10.0.0.2 -p 53 ip-10-0-1-121.eu-west-1.compute.internal.

; <<>> DiG 9.10.3-P4-Ubuntu <<>> A @10.0.0.2 -p 53 ip-10-0-1-121.eu-west-1.compute.internal.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44149
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ip-10-0-1-121.eu-west-1.compute.internal. IN A

;; ANSWER SECTION:
ip-10-0-1-121.eu-west-1.compute.internal. 20 IN	A 10.0.1.121

;; Query time: 1 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Tue Jul 04 07:27:22 UTC 2017
;; MSG SIZE  rcvd: 85
```

Hopes this helps

**Comment by nickdoikov** [comment]
@palsivertsen  we prepared container with fix for this issue . 
feel free to test it : 

```
yyyar/gobetween:issue-97
```

**Comment by shantanugadgil** [comment]
@nickdoikov on a side note, would you consider having a Docker image of "latest from master" on Docker Hub?
This would help to get the latest additions/enhancements/fixes from master until a new TAG appears.
For now I am making do with creating an image myself and hosting in locally in a private registry.

Thanks and Regards,
Shantanu

**Comment by palsivertsen** [comment]
@nickdoikov Seems to work as expected.
